/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./lib/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "garden-bg": "#FBF6F0",
        "garden-card": "#FFFCF8",
        "garden-primary": "#E08162",
        "garden-secondary": "#7F9B8F",
        "garden-text": "#3C322B",
        "garden-sub": "#7C736C",
        "garden-border": "#F0E6DD",
        "garden-muted": "#F6EFE8",
        "garden-accent": "#F3D7C9",
        "sunrise-bg": "#F6F8FC",
        "sunrise-card": "#FFFFFF",
        "sunrise-primary": "#7CB7FF",
        "sunrise-secondary": "#2F6FED",
        "sunrise-text": "#1E2433",
        "sunrise-sub": "#5F6B7A",
        "sunrise-border": "#D8E0EE",
        "sunrise-muted": "#EEF2F8",
        "sunrise-accent": "#FFD166",
        "focus-bg": "#F4F7F4",
        "focus-card": "#FFFFFF",
        "focus-primary": "#23B07B",
        "focus-secondary": "#1B5E7A",
        "focus-text": "#1E2A2F",
        "focus-sub": "#5C6B73",
        "focus-border": "#D9E4E0",
        "focus-muted": "#E9F0ED",
        "focus-accent": "#FFC857",
      },
    },
  },
  plugins: [],
};
